### ISSUE TITLE
The reproduced results differ significantly from the paper.

### ISSUE THREAD

**Issue by lxr-1204** [zmcheng9/GMRD#1]
Thank you very much for your excellent and solid work. I have read your article published in TPAMI. I used the chaost2 dataset and trained two versions, **setting1** and **setting2**, as required. As far as I know, the only difference between the scripts is that `exclude_label=None` in one and `exclude_label=[1,2,3,4]` in the other.  I have reproduced the code as per your request, and below are my training and validation scripts. **If there are any issues with my script, please be sure to let me know, especially as I would like to know whether it is necessary to try the best iteration model weight for each fold. I choose 36000.pth for each setting**

### Setting1 CHAOST2

| Fold | LIVER  | RK     | LK     | SPLEEN | Total Mean Dice |
|------|--------|--------|--------|--------|-----------------|
| 1    | 0.7989 | 0.9040 | 0.7348 | 0.5839 | 0.7554          |
| 2    | 0.7714 | 0.9019 | 0.8342 | 0.5952 | 0.7757          |
| 3    | 0.8275 | 0.9128 | 0.7995 | 0.8230 | 0.8407          |
| 4    | 0.8256 | 0.9147 | 0.7636 | 0.7653 | 0.8173          |
| 5    | 0.7836 | 0.8919 | 0.7007 | 0.7963 | 0.7931          |
| **Mean** | **0.8014** | **0.9051** | **0.7666** | **0.7127** | **0.7963**  |

### Setting2 CHAOST2

| Fold | LIVER  | RK     | LK     | SPLEEN | Total Mean Dice |
|------|--------|--------|--------|--------|-----------------|
| 1    | 0.8178 | 0.8968 | 0.7531 | 0.6005 | 0.7670          |
| 2    | 0.7421 | 0.8468 | 0.7725 | 0.5990 | 0.7401          |
| 3    | 0.8342 | 0.8850 | 0.7679 | 0.7895 | 0.8192          |
| 4    | 0.8256 | 0.8983 | 0.6733 | 0.7748 | 0.7930          |
| 5    | 0.7702 | 0.8786 | 0.6753 | 0.7593 | 0.7708          |
| **Mean** | **0.7980** | **0.8811** | **0.7284** | **0.7046** | **0.7780**  |

This table is from your paper report.
![image](https://github.com/user-attachments/assets/fc6be6fa-0dd8-4524-8dbb-f77d3152c89d)

![image](https://github.com/user-attachments/assets/2bc96ea3-3548-4fd5-8867-1cb100160d37)
![image](https://github.com/user-attachments/assets/b959253f-55c3-4821-8b36-4e8451c79815)

**Comment by zmcheng9** [comment]
This is the code before the paper was majorly revised, the final version hasn't been uploaded yet as it's still being tidied up.

I recommend you use an NVIDIA RTX 2080 Ti and remove get_aux_loss from the model code, which has not yet been refined. The Dice score after training will be at least 82 or higher.

I believe this helps!
